### ISSUE TITLE
ansible-pull does not apply modifications on client if `config` directory is absent

### ISSUE THREAD

**Issue by syntaxerrormmm** [syntaxerrormmm/ps-srvmgmt#23]
For some strange reasons, latest versions of Ansible does not download the repository before applying the `local.yml` playbook.

## Workaround ##

You can fix it manually downloading the first time the repository from the server with the following:
```
git clone -b <branch> git://pdc.<yourdomain>/client-pull-installation.git /var/lib/<yourdomain>/config
```
And then relaunching `/var/lib/<yourdomain>/bin/ansible-pull.sh` / restarting the client.

**Comment by leopoldotosi** [comment]
as well do on this way :-)(-:

```
/usr/bin/curl -sSL4 http://pdc.<yuordomain>/ks/preseed/postseed-docenti.sh | /bin/bash

git clone -b <branch> git://pdc.<yourdomain>/client-pull-installation.git /var/lib/<yourdomain>/config

/var/lib/<yuordomain>/bin/ansible-pull.sh
```

**Comment by syntaxerrormmm** [comment]
@leopoldotosi, relaunching the postseed scripts has no sense. The postseed script is called automatically at the end of the preseed procedure, so if your client has rebooted once, the postseed script has already been launched (and MAC address of the machine and hostname has been added to the Doraemon database).

`<yourdomain>` was only a placeholder for your domain. Inside the `master` branch, `<yourdomain>` is `topolin.ia`.
